#!/bin/sh

# Welcome to a fork of the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.


fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

append_to_zshrc() {
  local text="$1" zshrc
  local skip_new_line="${2:-0}"

  if [ -w "$HOME/.zshrc.local" ]; then
    zshrc="$HOME/.zshrc.local"
  else
    zshrc="$HOME/.zshrc"
  fi

  if ! grep -Fqs "$text" "$zshrc"; then
    if [ "$skip_new_line" -eq 1 ]; then
      printf "%s\n" "$text" >> "$zshrc"
    else
      printf "\n%s\n" "$text" >> "$zshrc"
    fi
  fi
}

create_folder_if_not_there() {
  local folder="$1"

  if [ -d "$folder" ]; then
    if ! [ -r "$folder" ]; then
      sudo chown -R "$LOGNAME:admin" "$folder"
    fi
  else
    sudo mkdir -p "$folder"
    sudo chflags norestricted "$folder"
    sudo chown -R "$LOGNAME:admin" "$folder"
  fi
}

is_app_installed() {
    local appNameOrBundleId=$1 bundleId

    # convert app name to bundle ID
    bundleId=$(osascript -e "id of application \"$appNameOrBundleId\"" 2>/dev/null) || { return 1; }

    # search for location of app with given bundle ID
    osascript -e "tell application \"Finder\" to POSIX path of (get application file id \"$bundleId\" as alias)" 2>/dev/null || { return 1; }
}

install_gui_app() {
  local appName="$1" caskName="$2"

  is_app_installed "$appName"
  if [ $? -eq 1 ]; then
    brew install --cask "$caskName"
  fi
}

# Check for Terminal running in ARM mode, install Rosetta, exit script
ARCH=$(arch)
if [[ "$ARCH" == "arm64" ]]; then
    /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    fancy_echo "\e[1;34m *** CodeClan - \e[1;31mAdditional manual steps required please visit - \033[0m"
    fancy_echo "https://github.com/codeclan/laptop/blob/master/apple_silicon.md"
    fancy_echo ""
    exit 0
fi

# Check for Xcode Devtools and wait for them to be installed before continuing
xcode-select -p 2>/dev/null
return_code=$?

while [ $return_code -eq 2 ]
do
  fancy_echo "\033[1;31mApple's Xcode Developer Tools are not installed!\033[0m"
  fancy_echo "\033[1;31mPlease install them through the dialog box before continuing with running this installation script.\033[0m"
  fancy_echo "Many of the tools used in this script will not work without the Xcode developer tools"
  fancy_echo "Opening 'Install Command Line Developer Tools'"
  xcode-select --install 1>/dev/null
  fancy_echo "Press enter to try again once Xcode developer tools are installed"
  read input
  xcode-select -p
  return_code=$?
done

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

# shellcheck disable=SC2016
append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'

HOMEBREW_PREFIX="/usr/local"
create_folder_if_not_there "$HOMEBREW_PREFIX"

case "$SHELL" in
  */zsh) : ;;
  *)
    fancy_echo "Changing your shell to zsh ..."
      chsh -s "$(which zsh)"
    ;;
esac


if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    append_to_zshrc '# recommended by brew doctor'

    # shellcheck disable=SC2016
    append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1

    export PATH="/usr/local/bin:$PATH"
fi

if brew list --formula | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=- <<EOF
tap "homebrew/services"
tap "homebrew/cask-fonts"

# Set permissions for installing from `brew bundle`
sudo chown -R $(whoami) /usr/local/lib/pkgconfig /usr/local/share/info /use/local/share/man/man3 /use/local/share/man/man5


fancy_echo "Downloading the R language"
curl -0 'https://cran.r-project.org/bin/macosx/R-3.6.0.pkg' > ./r_lang.pkg

fancy_echo "Installing the R language"
sudo installer -pkg r_lang.pkg -target /

brew tap adoptopenjdk/openjdk
brew cask install adoptopenjdk/openjdk/adoptopenjdk11
brew install jenv

echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(jenv init -)"' >> ~/.zshrc

jenv add /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
jenv versions
R CMD javareconf


# Unix
brew "git"
brew "zsh"
brew "node"

# Databases
brew "postgres", restart_service: true

# Fonts
cask "font-open-dyslexic"
EOF

fancy_echo "Installing Oh-My-Zsh ..."
curl -L \
  "https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh" | sh


fancy_echo "Installing GUI apps"

# Web browsing
install_gui_app "google chrome" "google-chrome"

# Navicat Data Modeler Essentials
install_gui_app "navicat data modeler essentials" "navicat-data-modeler-essentials"

# Text editing
install_gui_app "atom" "atom"

# Chat
install_gui_app "slack" "slack"

# Insomnia
install_gui_app "insomnia" "insomnia"

# MacDown
install_gui_app "macdown" "macdown"

# Github Desktop
install_gui_app "github desktop" "github"

# RStudio
install_gui_app "rstudio" "rstudio"

# Anaconda
install_gui_app "anaconda" "anaconda"
echo 'export PATH="/usr/local/anaconda3/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc


if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi

fancy_echo "Setting Atom as default text editor ..."
append_to_zshrc "export EDITOR='atom -nw'"
append_to_zshrc "export PAGER='less -f'"

fancy_echo "Rebinding # to the § key"
create_folder_if_not_there "$HOME/Library/KeyBindings"
MACOS_KEYMAP_FILE="$HOME/Library/KeyBindings/DefaultKeyBinding.dict"
touch "$MACOS_KEYMAP_FILE"
cat > "$MACOS_KEYMAP_FILE" << EOM
{
  /* Map '#' to the § key */
  "§" = ("insertText:", "#");
}
EOM

fancy_echo "Globally ignoring .DS_Store files"
echo .DS_Store >> ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global

fancy_echo "Setting default Git branch"
git config --global init.defaultBranch main

fancy_echo "Creating Postgres database under current user name"
if ! psql -lqt | cut -d \| -f 1 | grep -qw "$(whoami)" >/dev/null; then
  createdb "$(whoami)"
fi
createuser "postgres"

fancy_echo "Checking for unsuccessful installs"

curl --remote-name "https://raw.githubusercontent.com/codeclan/data_laptop_script/master/laptop_install_test"
sh laptop_install_test

fancy_echo "⚠️ Script has finished - please scroll the lines above and bring any errors to an instructor's attention during Meet Your Cohort ⚠️"
